### ISSUE TITLE
Access to insights page

### ISSUE THREAD

**Issue by glassnotes** [jerryxu9/CPEN-400Q-Project#1]
Hi @jerryxu9 thanks for giving me access to the repository! Could you please enable viewing of all "insights" so I can see the details about the contributors? Thanks!

**Comment by jerryxu9** [comment]
Hi professor @glassnotes , I don't think I can do so because I don't have GitHub pro. Do you want me to make the repo public? 
![Screenshot 2023-04-15 at 10 37 28](https://user-images.githubusercontent.com/54859894/232244775-1c9f7437-281e-43e1-8ae3-0312d0de3cc8.png)

**Comment by glassnotes** [comment]
Oh I see - if your teammates are comfortable with that you're welcome to make it public. Otherwise if one of them has a pro account perhaps you can transfer ownership / give them admin access and they can enable it?

**Comment by jerryxu9** [comment]
> Oh I see - if your teammates are comfortable with that you're welcome to make it public. Otherwise if one of them has a pro account perhaps you can transfer ownership / give them admin access and they can enable it?

Discussed with my teammates and just made the repo public.
